source 'https://supermarket.chef.io'

cookbook 'runit'
cookbook 'users'
cookbook 'sudo'
cookbook 'openssh'
cookbook 'ufw'
cookbook 'nodejs'
cookbook 'ncdu'
cookbook 'swap_tuning'

cookbook 'postgresql',   github: 'kirillshevch/postgresql'
cookbook 'nginx',        github: 'kirillshevch/nginx', ref: '2.7.7'
cookbook 'monit',        github: 'phlipper/chef-monit'
cookbook 'rvm',          github: 'martinisoft/chef-rvm', ref: 'v0.9.4'
cookbook 'redisio',      github: 'yakara-ltd/redisio', ref: 'systemd'
